# Generated by Django 2.0.6 on 2018-06-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_developer', models.CharField(max_length=100)),
                ('foundation', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('release_date', models.DateField()),
                ('system_requirements', models.TextField(max_length=1000)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.developer')),
            ],
        ),
    ]
